language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 1.8.7
  - 1.9.2
  - 2.0.0
  - 2.1.1
  - 2.2.2
env:
  - PUPPET_VERSION=3.8.1
  - PUPPET_VERSION=4.2.1
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
